# Generated by Django 5.0.4 on 2024-06-06 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_delete_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tasker",
        ),
    ]
