# Generated by Django 5.0.4 on 2024-06-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_delete_tasker"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
