# Generated by Django 5.0.4 on 2024-06-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_alter_userdata_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
