# Generated by Django 5.0.4 on 2024-06-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_userdata_is_verified_alter_userdata_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="otp_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
