# Generated by Django 5.0.4 on 2024-06-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_userdata_otp_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="blocked_for_tasker",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userdata",
            name="requested_to_tasker",
            field=models.BooleanField(default=False),
        ),
    ]
