# Generated by Django 5.0.4 on 2024-06-21 15:15

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="address",
            field=models.CharField(default="", max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(
                default="email", max_length=100, unique=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(max_length=180, verbose_name="City"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                default="Other",
                max_length=20,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=30, region=None, verbose_name="Phone Number"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_photo",
            field=models.ImageField(
                default="profile_default.png",
                upload_to="",
                verbose_name="Profile Photo",
            ),
        ),
    ]
