# Generated by Django 5.0.4 on 2024-06-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_profile_address_profile_email_alter_profile_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Phone Number"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_photo",
            field=models.ImageField(
                default="", upload_to="", verbose_name="Profile Photo"
            ),
        ),
    ]
