# Generated by Django 5.0.4 on 2024-06-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_alter_profile_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_photo",
            field=models.ImageField(
                default="", upload_to="profile_photos/", verbose_name="Profile Photo"
            ),
        ),
    ]
