# Generated by Django 5.0.4 on 2024-08-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_chat_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="image",
        ),
        migrations.AddField(
            model_name="chat",
            name="image_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
