# Generated by Django 5.0.4 on 2024-06-28 15:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "work_image",
                    models.ImageField(
                        default="", upload_to="work_image/", verbose_name="Work Image"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tasker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{10}$", message="Phone number must be 10 digits"
                            )
                        ],
                    ),
                ),
                (
                    "aadhar_number",
                    models.CharField(
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{12}$", message="Aadhar number must be 12 digits"
                            )
                        ],
                    ),
                ),
                ("address", models.TextField()),
                (
                    "work_photo",
                    models.ImageField(
                        default="", upload_to="work_photos/", verbose_name="Work Photo"
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasker_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskerWorkCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_charge",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "tasker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="task_workers.tasker",
                    ),
                ),
                (
                    "work_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="task_workers.workcategory",
                    ),
                ),
            ],
            options={
                "unique_together": {("tasker", "work_category")},
            },
        ),
        migrations.AddField(
            model_name="tasker",
            name="tasks",
            field=models.ManyToManyField(
                related_name="taskers",
                through="task_workers.TaskerWorkCategory",
                to="task_workers.workcategory",
            ),
        ),
    ]
