# Generated by Django 5.0.4 on 2024-06-29 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_workers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskerworkcategory",
            name="tasker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasker_work_categories",
                to="task_workers.tasker",
            ),
        ),
    ]
