# Generated by Django 5.0.4 on 2024-07-01 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_workers", "0002_alter_taskerworkcategory_tasker"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasker",
            name="tasks",
        ),
        migrations.AddField(
            model_name="tasker",
            name="task",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="task_workers.workcategory",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tasker",
            name="task_fee",
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="TaskerWorkCategory",
        ),
    ]
