# Generated by Django 5.0.4 on 2024-06-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "task_workers",
            "0002_remove_tasker_work_categories_remove_tasker_tasks_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="tasker",
            name="aadhar_number",
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
