# Generated by Django 5.0.4 on 2024-06-26 04:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_workers", "0003_tasker_aadhar_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasker",
            name="work_photo",
            field=models.ImageField(
                default="", upload_to="work_photos/", verbose_name="Work Photo"
            ),
        ),
        migrations.AddField(
            model_name="workcategory",
            name="work_image",
            field=models.ImageField(
                default="", upload_to="work_image/", verbose_name="Work Image"
            ),
        ),
        migrations.AlterField(
            model_name="tasker",
            name="aadhar_number",
            field=models.CharField(
                max_length=12,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{12}$", message="Aadhar number must be 12 digits"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tasker",
            name="phone_number",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{10}$", message="Phone number must be 10 digits"
                    )
                ],
            ),
        ),
    ]
